fertilizer_bot/ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_tf: true
        map_frame: map
        odom_frame: fertilizer_bot/odom
        base_link_frame: fertilizer_bot/base_link  
        world_frame: fertilizer_bot/odom           
        odom0: /fertilizer_bot/diffbot_base_controller/odom
        odom0_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, true,
                       false, false, false]
        odom0_differential: true
        odom1: /fertilizer_bot/visual_odom
        odom1_config: [true,  true,  false,
                       false, false, false,
                       false, false, false,
                       false, false, true,
                       false, false, false]
        odom1_differential: true
        # imu0: /fertilizer_bot/imu
        # imu0_config: [false, false, false,
        #               false,  false,  true,
        #               false, false, false,
        #               false,  false,  true,
        #               true,  false,  false]
        # imu0_differential: false
        