twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic    : harvesting_bot/cmd_vel
        timeout  : 0.5
        priority : 10
      keyboard:
        topic    : harvesting_bot/cmd_keyboard
        timeout  : 0.5
        priority : 100